# Generated by Django 4.2.7 on 2024-04-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_2',
            field=models.BooleanField(default=False, verbose_name='Доставлено'),
        ),
    ]
